#' Create a time snapshot from an OSM history file
#'
#' Filters objects from an OSM history file based on a specified point in time.
#' The output is a normal OSM data file containing the data as it would have
#' looked at the specified time (UTC).
#'
#' @param input_path A string. The path to the OSM history file to be filtered.
#'   Please see [file_formats] for a list of supported file formats.
#' @param timestamp A string, Date, or POSIXct. The timestamp in ISO 8601 format
#'   (e.g., "2015-01-01T00:00:00Z") representing the point in time for the snapshot.
#'   If a Date or POSIXct object is provided, it will be converted automatically.
#' @param output_path A string. The path to the file where the output should be
#'   written to. Please see [file_formats] for a list of supported file formats.
#' @param overwrite A logical. Whether existing files should be overwritten by
#'   the output. Defaults to `FALSE`.
#' @param echo_cmd A logical. Whether to print the Osmium command generated by
#'   the function call to the screen. Defaults to `FALSE`.
#' @param spinner A logical. Whether to show a reassuring spinner while the
#'   Osmium call is being executed. Defaults to `TRUE`.
#' @param verbose A logical. Whether to display detailed information on the
#'   running command. Defaults to `FALSE`.
#'
#' @return The normalized path to the output file.
#'
#' @examples \dontrun{
#' history_path <- system.file("extdata/cur.osm.pbf", package = "rosmium")
#' 
#' output <- time_filter(
#'   input_path = history_path,
#'   timestamp = as.Date("2015-01-01"),
#'   output_path = tempfile(fileext = ".osm.pbf")
#' )
#'
#' }
#' @export
time_filter <- function(input_path,
  timestamp,
  output_path,
  overwrite = FALSE,
  echo_cmd = FALSE,
  spinner = TRUE,
  verbose = FALSE) {
  assert_osmium_is_installed()

  checkmate::assert_file_exists(input_path)
  checkmate::assert_logical(overwrite, any.missing = FALSE, len = 1)
  checkmate::assert_logical(echo_cmd, any.missing = FALSE, len = 1)
  checkmate::assert_logical(spinner, any.missing = FALSE, len = 1)
  checkmate::assert_logical(verbose, any.missing = FALSE, len = 1)
  assert_output_path_multi_ext(output_path, overwrite)

  if (inherits(timestamp, c("Date", "POSIXct"))) {
    timestamp <- format(timestamp, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
  } else if (is.character(timestamp)) {
    # Check if the timestamp matches ISO 8601 format
    iso8601_pattern <- "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$"
    matches_format <- grepl(iso8601_pattern, timestamp)
  
    # Try converting to POSIXct as a second validation
    can_convert_to_posix <- !is.na(as.POSIXct(timestamp, format = "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"))
  
    if (!(matches_format && can_convert_to_posix)) {
      current_time_example <- format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
      stop(paste0("Invalid timestamp format. Please provide a valid ISO 8601 timestamp. For example: \"", current_time_example, "\""))
    }
  } else {
    stop(paste0("Invalid timestamp input. Must be a Date, POSIXct, or ISO 8601 formatted string (for example: \"", current_time_example, "\" )"))
  }
  
  

  output_arg <- paste0("--output=", output_path)
  overwrite_arg <- if (overwrite) "--overwrite" else character()
  verbose_arg <- if (verbose) "--verbose" else character()

  args <- c(
  "time-filter",
  input_path,
  timestamp,
  output_arg,
  overwrite_arg,
  verbose_arg
  )

  logs <- processx::run(
  "osmium",
  args,
  spinner = spinner,
  echo_cmd = echo_cmd,
  echo = verbose
  )

  return(normalizePath(output_path))
} 
