#' Create a time snapshot from an OSM history file
#'
#' Filters objects from an OSM history file based on a specified point or interval in time.
#' The output is a normal OSM data file containing the data as it would have looked at the specified time (UTC) or over the given interval.
#'
#' @param input_path A string. The path to the OSM history file to be filtered.
#'   Please see [file_formats] for a list of supported file formats.
#' @param timestamp A string, Date, or POSIXct, or a vector of two such values.
#'   The timestamp(s) in ISO 8601 format ('yyyy-mm-ddThh:mm:ssZ' e.g., "2015-01-01T00:00:00Z") representing the point in time for the snapshot or the start and end of a time interval.
#'   If Date or POSIXct objects are provided, they will be converted automatically to the required string format.
#'   **Note:** If two timestamps are provided and the first is later than the second, they will be swapped (with a warning) so that the interval is correct.
#' @param output_path A string. The path to the file where the output should be
#'   written to. Please see [file_formats] for a list of supported file formats.
#' @param overwrite A logical. Whether existing files should be overwritten by
#'   the output. Defaults to `FALSE`.
#' @param echo_cmd A logical. Whether to print the Osmium command generated by
#'   the function call to the screen. Defaults to `FALSE`.
#' @param echo A logical. Whether to print the standard output and error
#'   generated by the Osmium call to the screen. Defaults to `TRUE`.
#' @param spinner A logical. Whether to show a reassuring spinner while the
#'   Osmium call is being executed. Defaults to `TRUE`.
#' @param verbose A logical. Whether to display detailed information on the
#'   running command. Defaults to `FALSE`.
#'
#' @return The normalized path to the output file.
#'
#' @examplesIf identical(tolower(Sys.getenv("NOT_CRAN")), "true")
#' history_path <- system.file("extdata/cur.osm.pbf", package = "rosmium")
#'
#' # Single timestamp example:
#' output_single <- time_filter(
#'   input_path = history_path,
#'   timestamp = as.Date("2015-01-01"),
#'   output_path = tempfile(fileext = ".osm.pbf")
#' )
#'
#' # Two timestamps example:
#' output_interval <- time_filter(
#'   input_path = history_path,
#'   timestamp = c("2015-01-01T00:00:00Z", "2015-06-01T00:00:00Z"),
#'   output_path = tempfile(fileext = ".osm.pbf")
#' )
#' 
#' @export
time_filter <- function(
    input_path,
    timestamp,
    output_path,
    overwrite = FALSE,
    echo_cmd = FALSE,
    echo = TRUE,
    spinner = TRUE,
    verbose = FALSE) {
  assert_osmium_is_installed()

  checkmate::assert_file_exists(input_path)
  checkmate::assert_logical(overwrite, any.missing = FALSE, len = 1)
  checkmate::assert_logical(echo, any.missing = FALSE, len = 1)
  checkmate::assert_logical(echo_cmd, any.missing = FALSE, len = 1)
  checkmate::assert_logical(spinner, any.missing = FALSE, len = 1)
  checkmate::assert_logical(verbose, any.missing = FALSE, len = 1)
  assert_output_path_multi_ext(output_path, overwrite)

  # Use the current time as an example for error messages.
  current_time_example <- format(Sys.time(), "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")

  # Validate the class of timestamp input.
  if (!(is.character(timestamp) || inherits(timestamp, c("Date", "POSIXct")))) {
    stop(paste0(
      "Invalid timestamp input. Must be a Date, POSIXct, or ISO 8601 formatted string (for example: \"",
      current_time_example, "\")"
    ))
  }

  # Only allow one or two timestamps.
  if (length(timestamp) < 1 || length(timestamp) > 2) {
    stop("Invalid timestamp input. Must provide one or two timestamps.")
  }

  if (length(timestamp) == 2) {
    if ( grepl("osh\\.pbf$", basename(output_path)) == FALSE ) {
      warning("Two timestamps provided but the output file does not have an '.osh.pbf' extension; it is recommended to use a '.osh.pbf' extension for interval snapshots.")
    }
  }

  # Process timestamp(s)
  if (length(timestamp) == 1) {
    # Single timestamp provided.
    if (inherits(timestamp, c("Date", "POSIXct"))) {
      timestamp <- format(timestamp, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
    } else if (is.character(timestamp)) {
      # Check if the timestamp matches ISO 8601 format.
      iso8601_pattern <- "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$"
      matches_format <- grepl(iso8601_pattern, timestamp)

      # Try converting to POSIXct as a secondary validation.
      can_convert_to_posix <- !is.na(as.POSIXct(timestamp, format = "%Y-%m-%dT%H:%M:%SZ", tz = "UTC"))

      if (!(matches_format && can_convert_to_posix)) {
        stop(paste0(
          "Invalid timestamp format. Please provide a valid ISO 8601 timestamp. For example: \"",
          current_time_example, "\""
        ))
      }
    }
  } else {
    # Two timestamps provided.
    if (inherits(timestamp, c("Date", "POSIXct"))) {
      # Check order and swap if necessary.
      if (timestamp[1] > timestamp[2]) {
        warning("The first timestamp was later than the second. They were swapped automatically for you, next time please provide the timestamps in the correct order.")
        timestamp <- timestamp[c(2, 1)]
      }
      # Convert both timestamps to the required string format.
      timestamp <- format(timestamp, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
    } else if (is.character(timestamp)) {
      iso8601_pattern <- "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}Z$"
      if (!all(grepl(iso8601_pattern, timestamp))) {
        stop(paste0(
          "Invalid timestamp format. Please provide valid ISO 8601 timestamps. For example: \"",
          current_time_example, "\""
        ))
      }
      ts_posix <- as.POSIXct(timestamp, format = "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
      if (any(is.na(ts_posix))) {
        stop(paste0(
          "Invalid timestamp format. Please provide valid ISO 8601 timestamps. For example: \"",
          current_time_example, "\""
        ))
      }
      if (ts_posix[1] > ts_posix[2]) {
        warning("The first timestamp was later than the second. They were swapped automatically for you, next time please provide the timestamps in the correct order.")
        ts_posix <- ts_posix[c(2, 1)]
      }
      timestamp <- format(ts_posix, "%Y-%m-%dT%H:%M:%SZ", tz = "UTC")
    } else {
      stop(paste0(
        "Invalid timestamp input. Must be a Date, POSIXct, or ISO 8601 formatted string (for example: \"",
        current_time_example, "\")"
      ))
    }
  }

  output_arg <- paste0("--output=", output_path)
  overwrite_arg <- if (overwrite) "--overwrite" else character()
  verbose_arg <- if (verbose) "--verbose" else character()

  # Build the command arguments. If two timestamps are provided, they are inserted in order.
  args <- c(
    "time-filter",
    input_path,
    timestamp,
    output_arg,
    overwrite_arg,
    verbose_arg
  )

  logs <- processx::run(
    "osmium",
    args,
    echo = echo,
    spinner = spinner,
    echo_cmd = echo_cmd
  )

  return(normalizePath(output_path))
}
